### ISSUE TITLE
Average sequence rotation error 

### ISSUE THREAD

**Issue by wanyiming2017** [LearnerLee/KITTI-odometry-evaluation-tool#1]
Thanks for your sharing. The evaluation results are really comprehensive! Here, I have some question . I have read some papers which use kitti odometry. The evaluation result they give was in type of as follows:
• t: average translational RMSE drift (%) on a length of 100–800 m.
• r: average rotational RMSE drift (°/100 m) on a length of 100–800 m.

The results you give was:
Average sequence translation RMSE (%):    6.2131
Average sequence rotation error (deg/m):  0.0170
 I think the translation RMSE  are under the same evaluation, however, rotation error may not. I wonder whether it's right if I directly multiply  0.0170 by 100?

**Comment by LeoQLi** [comment]
Yes, you can multiply 0.0170 (°/m) by 100 to get 1.70 (°/100m).
