### ISSUE TITLE
Wrong direction

### ISSUE THREAD

**Issue by sunhufly** [LearnerLee/KITTI-odometry-evaluation-tool#9]
Thank you very much for your work.
but when I use this tool for drawing the trajectory, the direction of (x,y,z) seems not correct.
![07_path](https://user-images.githubusercontent.com/63384142/131069436-9b62b0bc-fd50-42ee-98d6-733788d94e80.png)
![07_path_3D](https://user-images.githubusercontent.com/63384142/131069458-57c810fa-5063-423e-abd2-6c8236ba2d68.png)
How can I solve this problem??
Whether  I use this in the wang way??

**Comment by xuwuzhou** [comment]
因为kitti真值的位姿是相机坐标系，你这个估计是激光算法生成的位姿，需要进行外参变化转成相机坐标系的位姿

**Comment by sunhufly** [comment]
非常感谢，外参变换以后确实可以了
